export const LIBS_CATEGORIES = [
  { id: "all", title: "All" },
  { id: "frontend", title: "Frontend" },
  { id: "backend", title: "Backend" },
  { id: "aiml", title: "AI / ML" },
  { id: "devops", title: "DevOps" },
  { id: "testing", title: "Testing" },
  { id: "mobile", title: "Mobile" },
  { id: "tools", title: "Tools" },
];

export const LIBS_DATA = [
  // ── Frontend ─────────────────────────────────────────────────────────────
  {
    id: "react",
    name: "React",
    description:
      "The library for building declarative, component-based UIs. Powers everything from startups to Meta.",
    category: "frontend",
    tags: ["ui", "components", "jsx", "hooks"],
    npm: "https://www.npmjs.com/package/react",
    github: "https://github.com/facebook/react",
    docs: "https://react.dev",
    weeklyDownloads: "60M+",
    icon: "SiReact",
    iconColor: "#61DAFB",
  },
  {
    id: "nextjs",
    name: "Next.js",
    description:
      "The React framework for production — SSR, SSG, API routes, and edge rendering in one package.",
    category: "frontend",
    tags: ["react", "ssr", "ssg", "fullstack"],
    npm: "https://www.npmjs.com/package/next",
    github: "https://github.com/vercel/next.js",
    docs: "https://nextjs.org/docs",
    weeklyDownloads: "8M+",
    icon: "SiNextdotjs",
    iconColor: "#000000",
  },
  {
    id: "vuejs",
    name: "Vue.js",
    description:
      "Progressive JavaScript framework with an approachable, performant, and versatile design.",
    category: "frontend",
    tags: ["ui", "composition-api", "reactive"],
    npm: "https://www.npmjs.com/package/vue",
    github: "https://github.com/vuejs/core",
    docs: "https://vuejs.org",
    weeklyDownloads: "5M+",
    icon: "SiVuedotjs",
    iconColor: "#42B883",
  },
  {
    id: "svelte",
    name: "Svelte",
    description:
      "A compiler-first UI framework that ships zero runtime — your components compile to vanilla JS.",
    category: "frontend",
    tags: ["compiler", "reactive", "no-virtual-dom"],
    npm: "https://www.npmjs.com/package/svelte",
    github: "https://github.com/sveltejs/svelte",
    docs: "https://svelte.dev",
    weeklyDownloads: "1.5M+",
    icon: "SiSvelte",
    iconColor: "#FF3E00",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    description:
      "Utility-first CSS framework that lets you build any design directly in your markup, fast.",
    category: "frontend",
    tags: ["css", "utility-first", "styling"],
    npm: "https://www.npmjs.com/package/tailwindcss",
    github: "https://github.com/tailwindlabs/tailwindcss",
    docs: "https://tailwindcss.com/docs",
    weeklyDownloads: "12M+",
    icon: "SiTailwindcss",
    iconColor: "#06B6D4",
  },
  {
    id: "framer-motion",
    name: "Framer Motion",
    description:
      "Production-ready animations for React — gesture support, layout animations, and exit transitions.",
    category: "frontend",
    tags: ["animation", "react", "gestures"],
    npm: "https://www.npmjs.com/package/framer-motion",
    github: "https://github.com/framer/motion",
    docs: "https://www.framer.com/motion",
    weeklyDownloads: "3M+",
    icon: "SiFramer",
    iconColor: "#0055FF",
  },
  {
    id: "redux",
    name: "Redux Toolkit",
    description:
      "The official, opinionated toolset for efficient Redux development — slices, thunks, and more.",
    category: "frontend",
    tags: ["state", "redux", "global-state"],
    npm: "https://www.npmjs.com/package/@reduxjs/toolkit",
    github: "https://github.com/reduxjs/redux-toolkit",
    docs: "https://redux-toolkit.js.org",
    weeklyDownloads: "4M+",
    icon: "SiRedux",
    iconColor: "#764ABC",
  },
  {
    id: "zustand",
    name: "Zustand",
    description:
      "Small, fast, and scalable state management with a bear-necessities API. No boilerplate.",
    category: "frontend",
    tags: ["state", "react", "lightweight"],
    npm: "https://www.npmjs.com/package/zustand",
    github: "https://github.com/pmndrs/zustand",
    docs: "https://zustand-demo.pmnd.rs",
    weeklyDownloads: "5M+",
    icon: "SiReact",
    iconColor: "#FF6B35",
  },

  // ── Backend ───────────────────────────────────────────────────────────────
  {
    id: "express",
    name: "Express.js",
    description:
      "Fast, unopinionated, minimalist web framework for Node.js. The de-facto standard for APIs.",
    category: "backend",
    tags: ["nodejs", "api", "rest", "middleware"],
    npm: "https://www.npmjs.com/package/express",
    github: "https://github.com/expressjs/express",
    docs: "https://expressjs.com",
    weeklyDownloads: "35M+",
    icon: "SiExpress",
    iconColor: "#000000",
  },
  {
    id: "nestjs",
    name: "NestJS",
    description:
      "Progressive Node.js framework with TypeScript-first architecture inspired by Angular — modules, decorators, DI.",
    category: "backend",
    tags: ["nodejs", "typescript", "decorators", "di"],
    npm: "https://www.npmjs.com/package/@nestjs/core",
    github: "https://github.com/nestjs/nest",
    docs: "https://docs.nestjs.com",
    weeklyDownloads: "2M+",
    icon: "SiNestjs",
    iconColor: "#E0234E",
  },
  {
    id: "fastify",
    name: "Fastify",
    description:
      "One of the fastest Node.js web frameworks — low overhead, powerful plugin system, schema validation.",
    category: "backend",
    tags: ["nodejs", "performance", "api"],
    npm: "https://www.npmjs.com/package/fastify",
    github: "https://github.com/fastify/fastify",
    docs: "https://fastify.dev",
    weeklyDownloads: "2.5M+",
    icon: "SiFastify",
    iconColor: "#000000",
  },
  {
    id: "django",
    name: "Django",
    description:
      "High-level Python web framework with batteries included — ORM, auth, admin panel out of the box.",
    category: "backend",
    tags: ["python", "orm", "auth", "fullstack"],
    npm: "https://pypi.org/project/Django",
    github: "https://github.com/django/django",
    docs: "https://docs.djangoproject.com",
    weeklyDownloads: "4M+",
    icon: "SiDjango",
    iconColor: "#092E20",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    description:
      "Modern, fast Python web framework for building APIs with automatic OpenAPI docs and type hints.",
    category: "backend",
    tags: ["python", "async", "openapi", "pydantic"],
    npm: "https://pypi.org/project/fastapi",
    github: "https://github.com/fastapi/fastapi",
    docs: "https://fastapi.tiangolo.com",
    weeklyDownloads: "5M+",
    icon: "SiFastapi",
    iconColor: "#009688",
  },
  {
    id: "prisma",
    name: "Prisma",
    description:
      "Next-generation ORM for Node.js and TypeScript — type-safe queries, migrations, and a great DX.",
    category: "backend",
    tags: ["orm", "typescript", "database", "migrations"],
    npm: "https://www.npmjs.com/package/prisma",
    github: "https://github.com/prisma/prisma",
    docs: "https://www.prisma.io/docs",
    weeklyDownloads: "3M+",
    icon: "SiPrisma",
    iconColor: "#2D3748",
  },

  // ── AI / ML ───────────────────────────────────────────────────────────────
  {
    id: "tensorflow",
    name: "TensorFlow",
    description:
      "End-to-end open-source ML platform by Google — from research to production deployment at scale.",
    category: "aiml",
    tags: ["deep-learning", "python", "gpu", "models"],
    npm: "https://www.npmjs.com/package/@tensorflow/tfjs",
    github: "https://github.com/tensorflow/tensorflow",
    docs: "https://www.tensorflow.org",
    weeklyDownloads: "1M+",
    icon: "SiTensorflow",
    iconColor: "#FF6F00",
  },
  {
    id: "pytorch",
    name: "PyTorch",
    description:
      "Flexible deep learning framework preferred by researchers — dynamic graphs, GPU acceleration, AutoGrad.",
    category: "aiml",
    tags: ["deep-learning", "python", "research", "cuda"],
    npm: "https://pypi.org/project/torch",
    github: "https://github.com/pytorch/pytorch",
    docs: "https://pytorch.org/docs",
    weeklyDownloads: "2M+",
    icon: "SiPytorch",
    iconColor: "#EE4C2C",
  },
  {
    id: "langchain",
    name: "LangChain",
    description:
      "Framework for building LLM-powered applications — chains, agents, memory, RAG pipelines, and more.",
    category: "aiml",
    tags: ["llm", "rag", "agents", "openai"],
    npm: "https://www.npmjs.com/package/langchain",
    github: "https://github.com/langchain-ai/langchainjs",
    docs: "https://js.langchain.com",
    weeklyDownloads: "500K+",
    icon: "SiReact",
    iconColor: "#1C3C3C",
  },
  {
    id: "openai-sdk",
    name: "OpenAI SDK",
    description:
      "Official TypeScript/Python client for the OpenAI API — chat completions, embeddings, vision, and assistants.",
    category: "aiml",
    tags: ["gpt", "api", "embeddings", "chat"],
    npm: "https://www.npmjs.com/package/openai",
    github: "https://github.com/openai/openai-node",
    docs: "https://platform.openai.com/docs",
    weeklyDownloads: "2M+",
    icon: "SiOpenai",
    iconColor: "#10A37F",
  },

  // ── DevOps ─────────────────────────────────────────────────────────────────
  {
    id: "docker",
    name: "Docker",
    description:
      "Containerize your apps once, run anywhere. Standard platform for packaging and shipping software.",
    category: "devops",
    tags: ["containers", "deployment", "images"],
    npm: "https://hub.docker.com",
    github: "https://github.com/docker/cli",
    docs: "https://docs.docker.com",
    weeklyDownloads: "Billions",
    icon: "SiDocker",
    iconColor: "#2496ED",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description:
      "Container orchestration at scale — automated rollouts, self-healing, service discovery, and load balancing.",
    category: "devops",
    tags: ["orchestration", "containers", "k8s", "cluster"],
    npm: "https://kubernetes.io",
    github: "https://github.com/kubernetes/kubernetes",
    docs: "https://kubernetes.io/docs",
    weeklyDownloads: "50M+",
    icon: "SiKubernetes",
    iconColor: "#326CE5",
  },
  {
    id: "terraform",
    name: "Terraform",
    description:
      "Infrastructure as code tool by HashiCorp — provision and manage cloud resources with declarative config.",
    category: "devops",
    tags: ["iac", "cloud", "aws", "provisioning"],
    npm: "https://www.terraform.io",
    github: "https://github.com/hashicorp/terraform",
    docs: "https://developer.hashicorp.com/terraform/docs",
    weeklyDownloads: "10M+",
    icon: "SiTerraform",
    iconColor: "#7B42BC",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    description:
      "Automate your CI/CD workflows directly in GitHub — build, test, and deploy on every push.",
    category: "devops",
    tags: ["ci-cd", "automation", "pipelines", "github"],
    npm: "https://github.com/features/actions",
    github: "https://github.com/actions",
    docs: "https://docs.github.com/en/actions",
    weeklyDownloads: "200M+ runs",
    icon: "SiGithubactions",
    iconColor: "#2088FF",
  },

  // ── Testing ───────────────────────────────────────────────────────────────
  {
    id: "jest",
    name: "Jest",
    description:
      "Delightful JavaScript testing framework with snapshot testing, code coverage, and zero config.",
    category: "testing",
    tags: ["unit", "snapshot", "coverage", "mocking"],
    npm: "https://www.npmjs.com/package/jest",
    github: "https://github.com/jestjs/jest",
    docs: "https://jestjs.io",
    weeklyDownloads: "25M+",
    icon: "SiJest",
    iconColor: "#C21325",
  },
  {
    id: "vitest",
    name: "Vitest",
    description:
      "Blazing fast unit test framework powered by Vite — Jest-compatible API with native ESM support.",
    category: "testing",
    tags: ["unit", "vite", "esm", "fast"],
    npm: "https://www.npmjs.com/package/vitest",
    github: "https://github.com/vitest-dev/vitest",
    docs: "https://vitest.dev",
    weeklyDownloads: "7M+",
    icon: "SiVitest",
    iconColor: "#6E9F18",
  },
  {
    id: "playwright",
    name: "Playwright",
    description:
      "End-to-end testing for modern web apps — cross-browser, auto-waiting, network mocking.",
    category: "testing",
    tags: ["e2e", "browser", "automation", "cross-browser"],
    npm: "https://www.npmjs.com/package/playwright",
    github: "https://github.com/microsoft/playwright",
    docs: "https://playwright.dev",
    weeklyDownloads: "4M+",
    icon: "SiPlaywright",
    iconColor: "#2EAD33",
  },

  // ── Mobile ────────────────────────────────────────────────────────────────
  {
    id: "react-native",
    name: "React Native",
    description:
      "Build native iOS and Android apps using React — one codebase, truly native output.",
    category: "mobile",
    tags: ["ios", "android", "cross-platform", "react"],
    npm: "https://www.npmjs.com/package/react-native",
    github: "https://github.com/facebook/react-native",
    docs: "https://reactnative.dev",
    weeklyDownloads: "3M+",
    icon: "SiReact",
    iconColor: "#61DAFB",
  },
  {
    id: "expo",
    name: "Expo",
    description:
      "Managed workflow for React Native — instant OTA updates, native APIs, EAS build and submit.",
    category: "mobile",
    tags: ["react-native", "eas", "ota", "cross-platform"],
    npm: "https://www.npmjs.com/package/expo",
    github: "https://github.com/expo/expo",
    docs: "https://docs.expo.dev",
    weeklyDownloads: "1M+",
    icon: "SiExpo",
    iconColor: "#000020",
  },
  {
    id: "flutter",
    name: "Flutter",
    description:
      "Google's UI toolkit for multi-platform apps from a single Dart codebase — iOS, Android, Web, Desktop.",
    category: "mobile",
    tags: ["dart", "cross-platform", "widgets", "google"],
    npm: "https://pub.dev/packages/flutter",
    github: "https://github.com/flutter/flutter",
    docs: "https://docs.flutter.dev",
    weeklyDownloads: "200K+",
    icon: "SiFlutter",
    iconColor: "#02569B",
  },

  // ── Tools ─────────────────────────────────────────────────────────────────
  {
    id: "vite",
    name: "Vite",
    description:
      "Next-generation frontend build tool — instant HMR, lightning-fast cold start, Rollup under the hood.",
    category: "tools",
    tags: ["build", "bundler", "hmr", "esm"],
    npm: "https://www.npmjs.com/package/vite",
    github: "https://github.com/vitejs/vite",
    docs: "https://vitejs.dev",
    weeklyDownloads: "15M+",
    icon: "SiVite",
    iconColor: "#646CFF",
  },
  {
    id: "eslint",
    name: "ESLint",
    description:
      "Pluggable linter for JavaScript and TypeScript — catches bugs, enforces style, integrates everywhere.",
    category: "tools",
    tags: ["linting", "code-quality", "typescript"],
    npm: "https://www.npmjs.com/package/eslint",
    github: "https://github.com/eslint/eslint",
    docs: "https://eslint.org",
    weeklyDownloads: "45M+",
    icon: "SiEslint",
    iconColor: "#4B32C3",
  },
  {
    id: "prettier",
    name: "Prettier",
    description:
      "Opinionated code formatter that enforces consistent style — stops all debates about formatting.",
    category: "tools",
    tags: ["formatter", "code-style", "auto-format"],
    npm: "https://www.npmjs.com/package/prettier",
    github: "https://github.com/prettier/prettier",
    docs: "https://prettier.io",
    weeklyDownloads: "35M+",
    icon: "SiPrettier",
    iconColor: "#F7B93E",
  },
  {
    id: "graphql",
    name: "GraphQL",
    description:
      "Query language for your API — ask for exactly what you need, get predictable results, strong typed schema.",
    category: "tools",
    tags: ["api", "schema", "queries", "type-safe"],
    npm: "https://www.npmjs.com/package/graphql",
    github: "https://github.com/graphql/graphql-js",
    docs: "https://graphql.org/learn",
    weeklyDownloads: "15M+",
    icon: "SiGraphql",
    iconColor: "#E10098",
  },
];
