export const TRACKS = {
  fullstack: [
    {
      id: "mern",
      title: "MERN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "React", "Node.js"],
    },
    {
      id: "pern",
      title: "PERN Developer",
      available: true,
      techs: ["PostgreSQL", "Express.js", "React", "Node.js"],
    },
    {
      id: "t3",
      title: "T3 Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Tailwind", "tRPC", "Prisma"],
    },
    {
      id: "fullstack-engineer",
      title: "Full Stack Engineer",
      available: true,
      techs: ["React", "Node.js", "SQL", "Docker"],
    },
    {
      id: "mean",
      title: "MEAN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "Angular", "Node.js"],
    },
    {
      id: "jamstack",
      title: "JAMstack Developer",
      available: true,
      techs: ["Next.js", "Gatsby", "Netlify", "Contentful"],
    },
    {
      id: "django-react",
      title: "Django + React Dev",
      available: true,
      techs: ["Python", "Django", "React", "PostgreSQL"],
    },
    {
      id: "rails-dev",
      title: "Ruby on Rails Dev",
      available: true,
      techs: ["Ruby", "Rails", "PostgreSQL", "Hotwire"],
    },
    {
      id: "next-fullstack",
      title: "Next.js Full Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Prisma", "Vercel"],
    },
    {
      id: "laravel-vue",
      title: "Laravel + Vue Dev",
      available: false,
      techs: ["PHP", "Laravel", "Vue 3", "MySQL"],
    },
  ],
  backend: [
    {
      id: "api-dev",
      title: "API Developer",
      available: true,
      techs: ["Node.js", "Express.js", "REST", "Postman"],
    },
    {
      id: "db-engineer",
      title: "DB Engineer",
      available: true,
      techs: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
    },
    {
      id: "systems-dev",
      title: "Systems Dev",
      available: true,
      techs: ["Rust", "C++", "Go", "Linux"],
    },
    {
      id: "security-dev",
      title: "Security Dev",
      available: true,
      techs: ["OAuth", "JWT", "OWASP", "Cryptography"],
    },
    {
      id: "graphql-dev",
      title: "GraphQL Developer",
      available: true,
      techs: ["GraphQL", "Apollo", "Node.js", "Prisma"],
    },
    {
      id: "microservices",
      title: "Microservices Engineer",
      available: true,
      techs: ["Docker", "Kubernetes", "RabbitMQ", "gRPC"],
    },
    {
      id: "go-dev",
      title: "Go Developer",
      available: true,
      techs: ["Go", "Gin", "PostgreSQL", "Docker"],
    },
    {
      id: "rust-dev",
      title: "Rust Developer",
      available: true,
      techs: ["Rust", "Actix", "WebAssembly", "Tokio"],
    },
    {
      id: "java-spring",
      title: "Java Spring Dev",
      available: true,
      techs: ["Java", "Spring Boot", "Maven", "Hibernate"],
    },
    {
      id: "python-backend",
      title: "Python Backend Dev",
      available: true,
      techs: ["Python", "FastAPI", "SQLAlchemy", "Celery"],
    },
    {
      id: "grpc-dev",
      title: "gRPC Engineer",
      available: true,
      techs: ["gRPC", "Protobuf", "Go", "Node.js"],
    },
    {
      id: "node-dev",
      title: "Node.js Developer",
      available: false,
      techs: ["Node.js", "TypeScript", "Fastify", "Prisma"],
    },
  ],
  mobile: [
    {
      id: "react-native",
      title: "React Native Dev",
      available: true,
      techs: ["React Native", "JavaScript", "Expo", "Redux"],
    },
    {
      id: "flutter",
      title: "Flutter Dev",
      available: true,
      techs: ["Flutter", "Dart", "Firebase", "Riverpod"],
    },
    {
      id: "ios",
      title: "iOS Dev",
      available: true,
      techs: ["Swift", "SwiftUI", "Xcode", "CoreData"],
    },
    {
      id: "android",
      title: "Android Dev",
      available: true,
      techs: ["Kotlin", "Jetpack Compose", "Android Studio", "Room"],
    },
    {
      id: "kotlin-dev",
      title: "Kotlin Developer",
      available: true,
      techs: ["Kotlin", "Coroutines", "Ktor", "Gradle"],
    },
    {
      id: "swift-dev",
      title: "Swift Developer",
      available: true,
      techs: ["Swift", "SwiftUI", "Combine", "Xcode"],
    },
    {
      id: "maui",
      title: ".NET MAUI Dev",
      available: true,
      techs: ["C#", ".NET MAUI", "XAML", "Azure"],
    },
    {
      id: "pwa-dev",
      title: "PWA Developer",
      available: true,
      techs: ["JavaScript", "Service Workers", "Web APIs", "Lighthouse"],
    },
    {
      id: "ionic",
      title: "Ionic Developer",
      available: false,
      techs: ["Ionic", "Angular", "Capacitor", "TypeScript"],
    },
  ],
  aiml: [
    {
      id: "ml-engineer",
      title: "ML Engineer",
      available: true,
      techs: ["Python", "TensorFlow", "PyTorch", "Scikit-learn"],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Pandas", "NumPy", "Matplotlib"],
    },
    {
      id: "ai-developer",
      title: "AI Developer",
      available: true,
      techs: ["Python", "LangChain", "OpenAI API", "FastAPI"],
    },
    {
      id: "nlp-engineer",
      title: "NLP Engineer",
      available: true,
      techs: ["Python", "HuggingFace", "spaCy", "NLTK"],
    },
    {
      id: "cv-engineer",
      title: "Computer Vision Engineer",
      available: true,
      techs: ["Python", "OpenCV", "YOLO", "PyTorch"],
    },
    {
      id: "llm-engineer",
      title: "LLM Engineer",
      available: true,
      techs: ["Python", "LangChain", "LlamaIndex", "Vector DBs"],
    },
    {
      id: "mlops",
      title: "MLOps Engineer",
      available: true,
      techs: ["MLflow", "Kubeflow", "Docker", "Airflow"],
    },
    {
      id: "data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "rl-engineer",
      title: "Reinforcement Learning Engineer",
      available: true,
      techs: ["Python", "OpenAI Gym", "Ray RLlib", "PyTorch"],
    },
    {
      id: "prompt-engineer",
      title: "Prompt Engineer",
      available: false,
      techs: ["LLMs", "LangChain", "Python", "RAG"],
    },
  ],
  devops: [
    {
      id: "cloud",
      title: "Cloud Engineer",
      available: true,
      techs: ["AWS", "Terraform", "Docker", "Linux"],
    },
    {
      id: "cicd",
      title: "CI/CD Engineer",
      available: true,
      techs: ["GitHub Actions", "Jenkins", "ArgoCD", "CircleCI"],
    },
    {
      id: "sre",
      title: "Site Reliability Engineer",
      available: true,
      techs: ["Prometheus", "Grafana", "PagerDuty", "Go"],
    },
    {
      id: "infra",
      title: "Infrastructure Dev",
      available: true,
      techs: ["Terraform", "Ansible", "Pulumi", "Linux"],
    },
    {
      id: "kubernetes",
      title: "Kubernetes Engineer",
      available: true,
      techs: ["Kubernetes", "Helm", "Istio", "Docker"],
    },
    {
      id: "aws-dev",
      title: "AWS Specialist",
      available: true,
      techs: ["EC2", "Lambda", "S3", "CloudFormation"],
    },
    {
      id: "gcp-dev",
      title: "GCP Specialist",
      available: true,
      techs: ["GKE", "BigQuery", "Cloud Run", "Pub/Sub"],
    },
    {
      id: "azure-dev",
      title: "Azure Specialist",
      available: true,
      techs: ["Azure DevOps", "AKS", "Bicep", "Azure Functions"],
    },
    {
      id: "devsecops",
      title: "DevSecOps Engineer",
      available: true,
      techs: ["Snyk", "Vault", "SonarQube", "Trivy"],
    },
    {
      id: "platform-engineer",
      title: "Platform Engineer",
      available: false,
      techs: ["Backstage", "Kubernetes", "Terraform", "ArgoCD"],
    },
  ],
  datascience: [
    {
      id: "data-analyst",
      title: "Data Analyst",
      available: true,
      techs: ["Python", "Pandas", "Excel", "Tableau"],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Scikit-learn", "NumPy", "Jupyter"],
    },
    {
      id: "data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "bi-developer",
      title: "BI Developer",
      available: true,
      techs: ["Power BI", "Tableau", "SQL", "DAX"],
    },
    {
      id: "ml-analyst",
      title: "ML Analyst",
      available: true,
      techs: ["Python", "Scikit-learn", "Pandas", "Matplotlib"],
    },
    {
      id: "data-architect",
      title: "Data Architect",
      available: true,
      techs: ["Snowflake", "BigQuery", "dbt", "SQL"],
    },
    {
      id: "analytics-engineer",
      title: "Analytics Engineer",
      available: true,
      techs: ["dbt", "SQL", "Looker", "Airflow"],
    },
    {
      id: "statistician",
      title: "Statistician",
      available: false,
      techs: ["R", "Python", "SPSS", "SAS"],
    },
  ],
  gamedev: [
    {
      id: "unity",
      title: "Unity Dev",
      available: true,
      techs: ["C#", "Unity", "Shader Graph", "Physics"],
    },
    {
      id: "unreal",
      title: "Unreal Dev",
      available: true,
      techs: ["C++", "Unreal Engine", "Blueprints", "Nanite"],
    },
    {
      id: "web-game",
      title: "Web Game Dev",
      available: true,
      techs: ["Phaser.js", "Three.js", "WebGL", "JavaScript"],
    },
    {
      id: "game-designer",
      title: "Game Designer",
      available: true,
      techs: ["Unity", "Figma", "Twine", "GDD"],
    },
    {
      id: "godot",
      title: "Godot Developer",
      available: true,
      techs: ["GDScript", "Godot", "C#", "Shaders"],
    },
    {
      id: "game-ai",
      title: "Game AI Developer",
      available: true,
      techs: ["C++", "Behavior Trees", "NavMesh", "GOAP"],
    },
    {
      id: "shader-dev",
      title: "Shader / Graphics Dev",
      available: true,
      techs: ["HLSL", "GLSL", "Vulkan", "Unity URP"],
    },
    {
      id: "game-backend",
      title: "Game Backend Dev",
      available: true,
      techs: ["Node.js", "WebSockets", "Redis", "PlayFab"],
    },
    {
      id: "xr-dev",
      title: "XR / AR / VR Dev",
      available: true,
      techs: ["Unity XR", "ARKit", "OpenXR", "WebXR"],
    },
    {
      id: "gameplay-engineer",
      title: "Gameplay Engineer",
      available: true,
      techs: ["C++", "Unreal", "C#", "Unity"],
    },
    {
      id: "tools-dev",
      title: "Game Tools Developer",
      available: false,
      techs: ["C#", "Python", "Unity Editor", "Qt"],
    },
  ],
  qa: [
    {
      id: "automation",
      title: "Automation Engineer",
      available: true,
      techs: ["Selenium", "Cypress", "Jest", "Playwright"],
    },
    {
      id: "manual",
      title: "Manual Tester",
      available: true,
      techs: ["Jira", "TestRail", "Postman", "BrowserStack"],
    },
    {
      id: "performance",
      title: "Performance Tester",
      available: true,
      techs: ["JMeter", "k6", "Grafana", "Locust"],
    },
    {
      id: "security-qa",
      title: "Security Tester",
      available: true,
      techs: ["Burp Suite", "OWASP ZAP", "Metasploit", "Nmap"],
    },
    {
      id: "mobile-qa",
      title: "Mobile QA Engineer",
      available: true,
      techs: ["Appium", "XCTest", "Espresso", "BrowserStack"],
    },
    {
      id: "api-qa",
      title: "API Tester",
      available: true,
      techs: ["Postman", "REST Assured", "Newman", "Swagger"],
    },
    {
      id: "sdet",
      title: "SDET",
      available: true,
      techs: ["Java", "Selenium", "TestNG", "CI/CD"],
    },
    {
      id: "chaos-engineer",
      title: "Chaos Engineer",
      available: true,
      techs: ["Chaos Monkey", "Gremlin", "Kubernetes", "Prometheus"],
    },
    {
      id: "accessibility-qa",
      title: "Accessibility Tester",
      available: true,
      techs: ["axe", "WCAG", "NVDA", "Lighthouse"],
    },
    {
      id: "qa-lead",
      title: "QA Lead",
      available: false,
      techs: ["Jira", "TestRail", "Agile", "CI/CD"],
    },
  ],
};
