export const TRACKS = {
  fullstack: [
    {
      id: "mern",
      title: "MERN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "React", "Node.js"],
    },
    {
      id: "pern",
      title: "PERN Developer",
      available: true,
      techs: ["PostgreSQL", "Express.js", "React", "Node.js"],
    },
    {
      id: "t3",
      title: "T3 Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Tailwind", "tRPC", "Prisma"],
    },
    {
      id: "fullstack-engineer",
      title: "Full Stack Engineer",
      available: true,
      techs: ["React", "Node.js", "SQL", "Docker"],
    },
    {
      id: "mean",
      title: "MEAN Developer",
      available: true,
      techs: ["MongoDB", "Express.js", "Angular", "Node.js"],
    },
    {
      id: "jamstack",
      title: "JAMstack Developer",
      available: true,
      techs: ["Next.js", "Gatsby", "Netlify", "Contentful"],
    },
    {
      id: "django-react",
      title: "Django + React Dev",
      available: true,
      techs: ["Python", "Django", "React", "PostgreSQL"],
    },
    {
      id: "rails-dev",
      title: "Ruby on Rails Dev",
      available: true,
      techs: ["Ruby", "Rails", "PostgreSQL", "Hotwire"],
    },
    {
      id: "next-fullstack",
      title: "Next.js Full Stack Dev",
      available: true,
      techs: ["Next.js", "TypeScript", "Prisma", "Vercel"],
    },
    {
      id: "laravel-vue",
      title: "Laravel + Vue Dev",
      available: false,
      techs: ["PHP", "Laravel", "Vue 3", "MySQL"],
    },
  ],
  backend: [
    {
      id: "api-dev",
      title: "API Developer",
      available: true,
      techs: ["Node.js", "Express.js", "REST", "Postman"],
    },
    {
      id: "db-engineer",
      title: "DB Engineer",
      available: true,
      techs: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
    },
    {
      id: "systems-dev",
      title: "Systems Dev",
      available: true,
      techs: ["Rust", "C++", "Go", "Linux"],
    },
    {
      id: "security-dev",
      title: "Security Dev",
      available: true,
      techs: ["OAuth", "JWT", "OWASP", "Cryptography"],
    },
    {
      id: "graphql-dev",
      title: "GraphQL Developer",
      available: true,
      techs: ["GraphQL", "Apollo", "Node.js", "Prisma"],
    },
    {
      id: "microservices",
      title: "Microservices Engineer",
      available: true,
      techs: ["Docker", "Kubernetes", "RabbitMQ", "gRPC"],
    },
    {
      id: "go-dev",
      title: "Go Developer",
      available: true,
      techs: ["Go", "Gin", "PostgreSQL", "Docker"],
    },
    {
      id: "rust-dev",
      title: "Rust Developer",
      available: true,
      techs: ["Rust", "Actix", "WebAssembly", "Tokio"],
    },
    {
      id: "java-spring",
      title: "Java Spring Dev",
      available: true,
      techs: ["Java", "Spring Boot", "Maven", "Hibernate"],
    },
    {
      id: "python-backend",
      title: "Python Backend Dev",
      available: true,
      techs: ["Python", "FastAPI", "SQLAlchemy", "Celery"],
    },
    {
      id: "grpc-dev",
      title: "gRPC Engineer",
      available: true,
      techs: ["gRPC", "Protobuf", "Go", "Node.js"],
    },
    {
      id: "node-dev",
      title: "Node.js Developer",
      available: false,
      techs: ["Node.js", "TypeScript", "Fastify", "Prisma"],
    },
  ],
  mobile: [
    {
      id: "react-native",
      title: "React Native Dev",
      available: true,
      techs: ["React Native", "JavaScript", "Expo", "Redux"],
    },
    {
      id: "flutter",
      title: "Flutter Dev",
      available: true,
      techs: ["Flutter", "Dart", "Firebase", "Riverpod"],
    },
    {
      id: "ios",
      title: "iOS Dev",
      available: true,
      techs: ["Swift", "SwiftUI", "Xcode", "CoreData"],
    },
    {
      id: "android",
      title: "Android Dev",
      available: true,
      techs: ["Kotlin", "Jetpack Compose", "Android Studio", "Room"],
    },
    {
      id: "kotlin-dev",
      title: "Kotlin Developer",
      available: true,
      techs: ["Kotlin", "Coroutines", "Ktor", "Gradle"],
    },
    {
      id: "swift-dev",
      title: "Swift Developer",
      available: true,
      techs: ["Swift", "SwiftUI", "Combine", "Xcode"],
    },
    {
      id: "maui",
      title: ".NET MAUI Dev",
      available: true,
      techs: ["C#", ".NET MAUI", "XAML", "Azure"],
    },
    {
      id: "pwa-dev",
      title: "PWA Developer",
      available: true,
      techs: ["JavaScript", "Service Workers", "Web APIs", "Lighthouse"],
    },
    {
      id: "ionic",
      title: "Ionic Developer",
      available: false,
      techs: ["Ionic", "Angular", "Capacitor", "TypeScript"],
    },
  ],
  aiml: [
    {
      id: "ml-engineer",
      title: "ML Engineer",
      available: true,
      techs: ["Python", "TensorFlow", "PyTorch", "Scikit-learn"],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Pandas", "NumPy", "Matplotlib"],
    },
    {
      id: "ai-developer",
      title: "AI Developer",
      available: true,
      techs: ["Python", "LangChain", "OpenAI API", "FastAPI"],
    },
    {
      id: "nlp-engineer",
      title: "NLP Engineer",
      available: true,
      techs: ["Python", "HuggingFace", "spaCy", "NLTK"],
    },
    {
      id: "cv-engineer",
      title: "Computer Vision Engineer",
      available: true,
      techs: ["Python", "OpenCV", "YOLO", "PyTorch"],
    },
    {
      id: "llm-engineer",
      title: "LLM Engineer",
      available: true,
      techs: ["Python", "LangChain", "LlamaIndex", "Vector DBs"],
    },
    {
      id: "mlops",
      title: "MLOps Engineer",
      available: true,
      techs: ["MLflow", "Kubeflow", "Docker", "Airflow"],
    },
    {
      id: "data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "rl-engineer",
      title: "Reinforcement Learning Engineer",
      available: true,
      techs: ["Python", "OpenAI Gym", "Ray RLlib", "PyTorch"],
    },
    {
      id: "prompt-engineer",
      title: "Prompt Engineer",
      available: false,
      techs: ["LLMs", "LangChain", "Python", "RAG"],
    },
  ],
  devops: [
    {
      id: "cloud",
      title: "Cloud Engineer",
      available: true,
      techs: ["AWS", "Terraform", "Docker", "Linux"],
    },
    {
      id: "cicd",
      title: "CI/CD Engineer",
      available: true,
      techs: ["GitHub Actions", "Jenkins", "ArgoCD", "CircleCI"],
    },
    {
      id: "sre",
      title: "Site Reliability Engineer",
      available: true,
      techs: ["Prometheus", "Grafana", "PagerDuty", "Go"],
    },
    {
      id: "infra",
      title: "Infrastructure Dev",
      available: true,
      techs: ["Terraform", "Ansible", "Pulumi", "Linux"],
    },
    {
      id: "kubernetes",
      title: "Kubernetes Engineer",
      available: true,
      techs: ["Kubernetes", "Helm", "Istio", "Docker"],
    },
    {
      id: "aws-dev",
      title: "AWS Specialist",
      available: true,
      techs: ["EC2", "Lambda", "S3", "CloudFormation"],
    },
    {
      id: "gcp-dev",
      title: "GCP Specialist",
      available: true,
      techs: ["GKE", "BigQuery", "Cloud Run", "Pub/Sub"],
    },
    {
      id: "azure-dev",
      title: "Azure Specialist",
      available: true,
      techs: ["Azure DevOps", "AKS", "Bicep", "Azure Functions"],
    },
    {
      id: "devsecops",
      title: "DevSecOps Engineer",
      available: true,
      techs: ["Snyk", "Vault", "SonarQube", "Trivy"],
    },
    {
      id: "platform-engineer",
      title: "Platform Engineer",
      available: false,
      techs: ["Backstage", "Kubernetes", "Terraform", "ArgoCD"],
    },
  ],
  datascience: [
    {
      id: "data-analyst",
      title: "Data Analyst",
      available: true,
      techs: ["Python", "Pandas", "Excel", "Tableau"],
    },
    {
      id: "data-scientist",
      title: "Data Scientist",
      available: true,
      techs: ["Python", "Scikit-learn", "NumPy", "Jupyter"],
    },
    {
      id: "data-engineer",
      title: "Data Engineer",
      available: true,
      techs: ["Spark", "Kafka", "Airflow", "dbt"],
    },
    {
      id: "bi-developer",
      title: "BI Developer",
      available: true,
      techs: ["Power BI", "Tableau", "SQL", "DAX"],
    },
    {
      id: "ml-analyst",
      title: "ML Analyst",
      available: true,
      techs: ["Python", "Scikit-learn", "Pandas", "Matplotlib"],
    },
    {
      id: "data-architect",
      title: "Data Architect",
      available: true,
      techs: ["Snowflake", "BigQuery", "dbt", "SQL"],
    },
    {
      id: "analytics-engineer",
      title: "Analytics Engineer",
      available: true,
      techs: ["dbt", "SQL", "Looker", "Airflow"],
    },
    {
      id: "statistician",
      title: "Statistician",
      available: false,
      techs: ["R", "Python", "SPSS", "SAS"],
    },
  ],
  gamedev: [
    {
      id: "unity",
      title: "Unity Dev",
      available: true,
      techs: ["C#", "Unity", "Shader Graph", "Physics"],
    },
    {
      id: "unreal",
      title: "Unreal Dev",
      available: true,
      techs: ["C++", "Unreal Engine", "Blueprints", "Nanite"],
    },
    {
      id: "web-game",
      title: "Web Game Dev",
      available: true,
      techs: ["Phaser.js", "Three.js", "WebGL", "JavaScript"],
    },
    {
      id: "game-designer",
      title: "Game Designer",
      available: true,
      techs: ["Unity", "Figma", "Twine", "GDD"],
    },
    {
      id: "godot",
      title: "Godot Developer",
      available: true,
      techs: ["GDScript", "Godot", "C#", "Shaders"],
    },
    {
      id: "game-ai",
      title: "Game AI Developer",
      available: true,
      techs: ["C++", "Behavior Trees", "NavMesh", "GOAP"],
    },
    {
      id: "shader-dev",
      title: "Shader / Graphics Dev",
      available: true,
      techs: ["HLSL", "GLSL", "Vulkan", "Unity URP"],
    },
    {
      id: "game-backend",
      title: "Game Backend Dev",
      available: true,
      techs: ["Node.js", "WebSockets", "Redis", "PlayFab"],
    },
    {
      id: "xr-dev",
      title: "XR / AR / VR Dev",
      available: true,
      techs: ["Unity XR", "ARKit", "OpenXR", "WebXR"],
    },
    {
      id: "gameplay-engineer",
      title: "Gameplay Engineer",
      available: true,
      techs: ["C++", "Unreal", "C#", "Unity"],
    },
    {
      id: "tools-dev",
      title: "Game Tools Developer",
      available: false,
      techs: ["C#", "Python", "Unity Editor", "Qt"],
    },
  ],
  qa: [
    {
      id: "automation",
      title: "Automation Engineer",
      available: true,
      techs: ["Selenium", "Cypress", "Jest", "Playwright"],
    },
    {
      id: "manual",
      title: "Manual Tester",
      available: true,
      techs: ["Jira", "TestRail", "Postman", "BrowserStack"],
    },
    {
      id: "performance",
      title: "Performance Tester",
      available: true,
      techs: ["JMeter", "k6", "Grafana", "Locust"],
    },
    {
      id: "security-qa",
      title: "Security Tester",
      available: true,
      techs: ["Burp Suite", "OWASP ZAP", "Metasploit", "Nmap"],
    },
    {
      id: "mobile-qa",
      title: "Mobile QA Engineer",
      available: true,
      techs: ["Appium", "XCTest", "Espresso", "BrowserStack"],
    },
    {
      id: "api-qa",
      title: "API Tester",
      available: true,
      techs: ["Postman", "REST Assured", "Newman", "Swagger"],
    },
    {
      id: "sdet",
      title: "SDET",
      available: true,
      techs: ["Java", "Selenium", "TestNG", "CI/CD"],
    },
    {
      id: "chaos-engineer",
      title: "Chaos Engineer",
      available: true,
      techs: ["Chaos Monkey", "Gremlin", "Kubernetes", "Prometheus"],
    },
    {
      id: "accessibility-qa",
      title: "Accessibility Tester",
      available: true,
      techs: ["axe", "WCAG", "NVDA", "Lighthouse"],
    },
    {
      id: "qa-lead",
      title: "QA Lead",
      available: false,
      techs: ["Jira", "TestRail", "Agile", "CI/CD"],
    },
  ],
};

// ─── Layer Schema ────────────────────────────────────────────────────────────
// {
//   id: string
//   title: string
//   order: number
//   techs: string[]
//   description: string
//   topics: string[]
//   resources: { label: string, platform: string, type: "docs"|"course"|"video"|"book" }[]
//   challenge: string        — hands-on mini project for this layer
//   estimatedTime: string
// }
// ─────────────────────────────────────────────────────────────────────────────

export const ROADMAPS = {
  mern: [
    {
      id: "mern-1",
      title: "Web Fundamentals",
      order: 1,
      techs: ["HTML", "CSS", "JavaScript"],
      description:
        "The foundation of everything web. Learn how browsers render pages, how to structure content with HTML, style it with CSS, and add interactivity with JavaScript.",
      topics: [
        "HTML5 semantic elements & accessibility",
        "CSS box model, flexbox, grid",
        "CSS responsive design & media queries",
        "JavaScript variables, types, functions",
        "DOM manipulation & events",
        "Browser DevTools basics",
      ],
      resources: [
        { label: "MDN Web Docs — HTML", platform: "MDN", type: "docs" },
        { label: "MDN Web Docs — CSS", platform: "MDN", type: "docs" },
        { label: "JavaScript.info", platform: "javascript.info", type: "docs" },
        { label: "The Odin Project — Foundations", platform: "The Odin Project", type: "course" },
        { label: "CSS Tricks — Flexbox Guide", platform: "CSS Tricks", type: "docs" },
      ],
      challenge: "Build a fully responsive personal portfolio page using only HTML & CSS.",
      estimatedTime: "2–3 weeks",
    },
    {
      id: "mern-2",
      title: "JavaScript Deep Dive",
      order: 2,
      techs: ["ES6+", "Async/Await", "Fetch API"],
      description:
        "Go beyond the basics. Master modern JavaScript features, asynchronous patterns, and how to communicate with external APIs.",
      topics: [
        "ES6+ — destructuring, spread, arrow functions, modules",
        "Closures, scope & the prototype chain",
        "Promises & async/await",
        "Fetch API & error handling",
        "Array methods — map, filter, reduce",
        "Event loop & call stack",
      ],
      resources: [
        { label: "You Don't Know JS (book series)", platform: "GitHub / O'Reilly", type: "book" },
        { label: "JavaScript.info — Advanced", platform: "javascript.info", type: "docs" },
        { label: "Fireship — JS in 100 Seconds", platform: "YouTube", type: "video" },
        { label: "Frontend Masters — JavaScript", platform: "Frontend Masters", type: "course" },
      ],
      challenge: "Build a weather app that fetches live data from a public API and handles loading/error states.",
      estimatedTime: "2–3 weeks",
    },
    {
      id: "mern-3",
      title: "React Fundamentals",
      order: 3,
      techs: ["React", "JSX", "Props", "useState"],
      description:
        "Learn how to think in components. Build dynamic UIs with React, understand the component lifecycle, and manage local state.",
      topics: [
        "JSX syntax & expressions",
        "Functional components & props",
        "useState & useEffect hooks",
        "Conditional rendering & lists",
        "Handling forms & controlled inputs",
        "Component composition patterns",
      ],
      resources: [
        { label: "React Official Docs", platform: "react.dev", type: "docs" },
        { label: "Scrimba — Learn React", platform: "Scrimba", type: "course" },
        { label: "The Odin Project — React", platform: "The Odin Project", type: "course" },
        { label: "Codevolution — React Tutorial", platform: "YouTube", type: "video" },
      ],
      challenge: "Build a task manager app with add, delete, and filter functionality — no backend yet.",
      estimatedTime: "3–4 weeks",
    },
    {
      id: "mern-4",
      title: "React Advanced",
      order: 4,
      techs: ["useContext", "React Router", "Custom Hooks"],
      description:
        "Level up your React skills with global state management, client-side routing, and reusable hook patterns.",
      topics: [
        "useContext & the Context API",
        "useReducer for complex state",
        "Custom hooks & reusability",
        "React Router v6 — nested routes, params",
        "Code splitting & lazy loading",
        "Performance — useMemo, useCallback, React.memo",
      ],
      resources: [
        { label: "React Router Official Docs", platform: "reactrouter.com", type: "docs" },
        { label: "Jack Herrington — Custom Hooks", platform: "YouTube", type: "video" },
        { label: "Frontend Masters — React Performance", platform: "Frontend Masters", type: "course" },
      ],
      challenge: "Extend your task manager with multi-page routing, a global theme toggle, and persisted state.",
      estimatedTime: "2–3 weeks",
    },
    {
      id: "mern-5",
      title: "Node.js & Express",
      order: 5,
      techs: ["Node.js", "Express.js", "REST", "Middleware"],
      description:
        "Move to the server. Build REST APIs with Node.js and Express, understand middleware, and handle routing and error management.",
      topics: [
        "Node.js runtime & module system (CommonJS / ESM)",
        "Express setup, routing & controllers",
        "Middleware — logging, validation, error handling",
        "RESTful API design & HTTP methods",
        "Environment variables & dotenv",
        "Working with the file system",
      ],
      resources: [
        { label: "Node.js Official Docs", platform: "nodejs.org", type: "docs" },
        { label: "Express Official Docs", platform: "expressjs.com", type: "docs" },
        { label: "Traversy Media — Express Crash Course", platform: "YouTube", type: "video" },
        { label: "The Odin Project — NodeJS", platform: "The Odin Project", type: "course" },
      ],
      challenge: "Build a REST API for a blog — CRUD endpoints for posts, with input validation and error handling.",
      estimatedTime: "2–3 weeks",
    },
    {
      id: "mern-6",
      title: "MongoDB & Mongoose",
      order: 6,
      techs: ["MongoDB", "Mongoose", "Atlas"],
      description:
        "Persist your data. Learn NoSQL database design, connect MongoDB to your Express app, and model data with Mongoose schemas.",
      topics: [
        "NoSQL vs SQL — when to use MongoDB",
        "MongoDB Atlas setup & cloud hosting",
        "CRUD operations with the MongoDB driver",
        "Mongoose schemas, models & validation",
        "Relationships — embedding vs referencing",
        "Indexing & query performance basics",
      ],
      resources: [
        { label: "MongoDB Official Docs", platform: "mongodb.com", type: "docs" },
        { label: "Mongoose Official Docs", platform: "mongoosejs.com", type: "docs" },
        { label: "Web Dev Simplified — MongoDB Crash Course", platform: "YouTube", type: "video" },
      ],
      challenge: "Add a MongoDB database to your blog API — store posts and authors with a proper schema and relationships.",
      estimatedTime: "2 weeks",
    },
    {
      id: "mern-7",
      title: "Authentication & Security",
      order: 7,
      techs: ["JWT", "bcrypt", "Cookies", "CORS"],
      description:
        "Secure your app. Implement user registration and login, hash passwords, issue JWTs, and protect routes.",
      topics: [
        "Password hashing with bcrypt",
        "JWT — signing, verifying, refresh tokens",
        "Auth middleware & protected routes",
        "HTTP-only cookies vs localStorage",
        "CORS configuration",
        "Input sanitization & basic OWASP awareness",
      ],
      resources: [
        { label: "JWT.io — Introduction", platform: "jwt.io", type: "docs" },
        { label: "Web Dev Simplified — JWT Auth", platform: "YouTube", type: "video" },
        { label: "OWASP Top 10", platform: "owasp.org", type: "docs" },
      ],
      challenge: "Add full auth to your blog API — register, login, JWT issuance, and protected post creation routes.",
      estimatedTime: "2 weeks",
    },
    {
      id: "mern-8",
      title: "Full Stack Integration",
      order: 8,
      techs: ["Axios", "React Query", "Zustand"],
      description:
        "Connect your React frontend to your Express backend. Handle API calls, loading states, caching, and global state across the full stack.",
      topics: [
        "Axios setup & interceptors",
        "React Query — queries, mutations, caching",
        "Global state with Zustand",
        "Handling auth tokens on the client",
        "Proxy config for local dev (Vite / CRA)",
        "Error boundaries & toast notifications",
      ],
      resources: [
        { label: "TanStack Query Docs", platform: "tanstack.com", type: "docs" },
        { label: "Zustand Docs", platform: "GitHub / npm", type: "docs" },
        { label: "Jack Herrington — React Query", platform: "YouTube", type: "video" },
      ],
      challenge: "Build a full MERN blog — React frontend that talks to your Express/MongoDB backend with auth, protected routes, and optimistic UI.",
      estimatedTime: "3–4 weeks",
    },
    {
      id: "mern-9",
      title: "Testing",
      order: 9,
      techs: ["Jest", "React Testing Library", "Supertest"],
      description:
        "Write tests that give you confidence. Cover your React components, API endpoints, and async logic.",
      topics: [
        "Unit testing with Jest",
        "React Testing Library — render, queries, events",
        "Testing async code & mocking",
        "API endpoint testing with Supertest",
        "Test coverage & CI integration",
        "Test-driven development basics",
      ],
      resources: [
        { label: "Jest Official Docs", platform: "jestjs.io", type: "docs" },
        { label: "React Testing Library Docs", platform: "testing-library.com", type: "docs" },
        { label: "Kent C. Dodds — Testing JavaScript", platform: "testingjavascript.com", type: "course" },
      ],
      challenge: "Write unit + integration tests for your blog app — cover components, API routes, and auth flow.",
      estimatedTime: "2 weeks",
    },
    {
      id: "mern-10",
      title: "Deployment & DevOps",
      order: 10,
      techs: ["Vercel", "Railway", "Docker", "GitHub Actions"],
      description:
        "Ship your app to the world. Deploy your frontend and backend, automate with CI/CD, and containerize with Docker.",
      topics: [
        "Deploying React to Vercel / Netlify",
        "Deploying Express API to Railway / Render",
        "Environment variables in production",
        "Docker basics — Dockerfile, images, containers",
        "GitHub Actions — CI pipeline on push",
        "Domain setup & HTTPS basics",
      ],
      resources: [
        { label: "Vercel Docs", platform: "vercel.com", type: "docs" },
        { label: "Railway Docs", platform: "railway.app", type: "docs" },
        { label: "TechWorld with Nana — Docker for Beginners", platform: "YouTube", type: "video" },
        { label: "GitHub Actions Docs", platform: "GitHub", type: "docs" },
      ],
      challenge: "Deploy your full MERN blog app — frontend on Vercel, API on Railway, MongoDB on Atlas, with a GitHub Actions CI pipeline.",
      estimatedTime: "1–2 weeks",
    },
  ],
};
